- name: Provision an EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning
  roles:
    - role: launch
      name: ami_build
  
- name: Deploy the application
  hosts: ami_build
  vars:
     ansible_ssh_user: "ubuntu"
     ansible_ssh_private_key_file: "~/.ssh/{{ec2_keypair}}.pem"
     ansible_ssh_port: 22
  roles:
    - dependency
    - cuda
    - mxnet

- name : Build AMI
  hosts: localhost
  connection: local
  gather_facts: True
  tasks:
    - name: Create AMI
      ec2_ami:
        instance_id: "{{ item.id }}"
        region: "{{ ec2_region }}"
        wait: no
        name: "{{ Your AMI name }}" # need th modify
        state: present
      register: ami
      with_items: "{{ ec2.instances }}"
