- name: Launch the new EC2 Instance
  local_action: 
    module: ec2
    group: "{{ ec2_security_group }}" 
    instance_type: "{{ ec2_instance_type}}"
    instance_tags: '{"Name":"{{ec2_tag_Name}}", "Type":"{{ec2_tag_Type}}", "Enviroment":"{{ec2_tag_Environment}}"}'
    image: "{{ ec2_image }}"
    wait: true
    region: "{{ ec2_region }}"
    keypair: "{{ ec2_keypair }}"
    count: "{{ec2_count}}"
    volumes:
       - device_name: /dev/sda1
         device_type: gp2
         volume_size: "{{ec2_volume_size}}"
         delete_on_termination: true        
  register: ec2

- name: Add new instances to host group
  add_host:
    name: "{{ item.public_dns_name }}"
    groupname: "ami_build"
    ec2_id: "{{ item.id }}"
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  local_action: wait_for
                host={{ item.public_ip }}
                port=22
                state=started
  with_items: "{{ ec2.instances }}"
