- name: Clone Mxnet Repo
  git:
    repo: https://github.com/dmlc/mxnet.git
    dest: /home/ubuntu/mxnet
    version: 58dec8b0a4a616ea2bd65b9ec4e0d2177b6c3d93 # can choose the version which you consider stable

- file: state=link src=/dev/null dest=/dev/raw1394
  sudo: true

- name: Move the config file location
  shell: "cd /home/ubuntu/mxnet; cp make/config.mk ."

- name: Overwrite mxnet config.mk | config
  replace: dest=/home/ubuntu/mxnet/config.mk regexp="^({{ item }})\s*=\s*0" replace='\1 = 1'
  with_items:
    - USE_CUDA
    - USE_CUDNN
    - USE_DIST_KVSTORE
    - USE_S3

- name: Overwrite mxnet config.mk | cuda path
  replace: dest=/home/ubuntu/mxnet/config.mk regexp="^(USE_CUDA_PATH)\s*=\s*NONE" replace='\1 = /usr/local/cuda-7.5'

- name: Build mxnet
  shell: "cd /home/ubuntu/mxnet; make -j$(nproc)"

- name: Install mxnet
  shell: "cd /home/ubuntu/mxnet/python; sudo python setup.py install"
